service_name: travis-ci
# For public repos on Travis, no repo_token is required. For private repos, set
# COVERALLS_REPO_TOKEN in Travis CI settings (do not commit it here).
service_name: travis-pro

